<a href="https://colab.research.google.com/github/Pavitra-khare/DA6401_Deep_learning/blob/main/DA6401_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install keras


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 kB 134.7 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 258.9 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 146.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.4/670.4 kB 200.8 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 335.8/335.8 kB 178.3 kB/s eta 0:00:0000:0100:01


In [ ]:
!pip install tensorflow


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.6/239.6 MB 167.4 kB/s eta 0:00:0000:0100:39
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 225.8 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 159.4 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 202.9 kB/s eta 0:00:0000:0100:04
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.1/405.1 kB 121.1 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 kB 186.8 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 164.7 kB/s eta 0:00:0000:0100:01
  Attempting uninstall: ml-dtypes
    Found existing installation: ml_dtypes 0.5.1
    Uninstalling ml_dtypes-0.5.1:
      Successfully uninstalled ml_dtypes-0.5.1


In [4]:
!pip install wandb

In [6]:
!wandb login

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: 3628-pavitrakhare (3628-pavitrakhare-indian-institute-of-technology-madras) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [30]:
import numpy as np
from keras.datasets import fashion_mnist
import wandb

wandb.init(project="DA6401-assignment-1", name="Ques-1")

labels = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
          'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

(images, labels_index), _ = fashion_mnist.load_data()
images = images.astype(np.float32) / 255.0

samples = {}
for image, label in zip(images, labels_index):
    if label not in samples:
        samples[label] = image
    if len(samples) == len(labels):
        break

wandb.log({"fashion_mnist_images": [wandb.Image(samples[label], caption=labels[label]) for label in samples]})



# QUESTION 2

In [32]:
def activation_sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [33]:
def softmax(x):
    exp_values = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_values / np.sum(exp_values, axis=1, keepdims=True)

In [37]:
def create_hidden_layers(no_of_hidden_layers, neurons_per_layer):

    return [neurons_per_layer] * no_of_hidden_layers

In [41]:
def propagate(input_data, weights_map, biases_map):

    activations = input_data.reshape(input_data.shape[0], -1)

    for layer in range(len(weights_map) - 1):
        activations = activation_sigmoid(np.dot(activations, weights_map[layer]) + biases_map[layer])

    final_input = np.dot(activations, weights_map[len(weights_map) - 1]) + biases_map[len(weights_map) - 1]
    probabilities = softmax(final_input)

    return probabilities

In [49]:
def forward_propagation(no_of_hidden_layer,neuron_per_hidden_layer):

  hidden_layers = create_hidden_layers(no_of_hidden_layer,neuron_per_hidden_layer)
  inputSize=28*28
  outputSize=10

  np.random.seed(42)

  layerStructure = [inputSize] + hidden_layers + [outputSize]

  weights_map = {i: np.random.randn(layerStructure[i], layerStructure[i+1]) * 0.01
                   for i in range(len(layerStructure) - 1)}

  biases_map = {i: np.zeros((1, layerStructure[i+1]))
                  for i in range(len(layerStructure) - 1)}

  predictions = propagate(images, weights_map, biases_map)

  print("probability distributions\n", predictions)

forward_propagation(3,64)

probability distributions
 [[0.10266086 0.09685557 0.10222774 ... 0.10299232 0.09947045 0.09417506]
 [0.10266104 0.09685557 0.10222772 ... 0.10299222 0.09947048 0.09417511]
 [0.1026611  0.0968556  0.10222775 ... 0.10299216 0.09947049 0.09417495]
 ...
 [0.10266103 0.09685565 0.1022277  ... 0.10299223 0.0994704  0.09417498]
 [0.10266105 0.09685561 0.10222772 ... 0.10299218 0.09947049 0.09417498]
 [0.10266107 0.09685569 0.10222768 ... 0.10299217 0.09947053 0.09417497]]


# QUESTION 3
